CREATE TABLE accounts (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          titular_name VARCHAR(100) NOT NULL,
                          balance NUMERIC(19,2) NOT NULL
);