CREATE TABLE transfers (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           value NUMERIC(19,2) NOT NULL,
                           source_account_id INTEGER NOT NULL,
                           destination_account_id INTEGER NOT NULL,
                           timestamp TIMESTAMP NOT NULL,
                           CONSTRAINT fk_source FOREIGN KEY (source_account_id) REFERENCES accounts(id),
                           CONSTRAINT fk_destination FOREIGN KEY (destination_account_id) REFERENCES accounts(id)
);